### ISSUE TITLE
搜番功能无效，Cloudflare保护

### ISSUE THREAD

**Issue by zx900930** [Angel-Hair/XUN_Bot#5]
动漫花园加了cloudflare反DDOS保护
request是无法执行js的所以永远返回空值

可以用selenium的webdriver等待5秒然后再抓取
但是headless模式会被cloudflare识别成bot
而且使用多了会弹出reCAPTCHA验证

建议改用蜜柑计划
例子：
https://mikanani.me/Home/Search?searchstr=%E9%AD%94%E7%8E%8B

**Comment by Angel-Hair** [comment]
非常感谢你的提醒和提供的思路，很久没用这个功能了，都不知道动漫花园加了cloudflare……
不过我用的其它方法解决的，虽然搜索页面加了cloudflare，但是提供的RSS订阅并没有受此限制，所以可以通过rss获得信息，更详细的信息直接通过rss提供的url转二级爬取获得，实际上我最开始的思路就是这个，这样可以获取更多的信息，不过当时因为rss的响应时间慢的原因没有采用_(:3 」∠)_

```python
# 动漫花园 rss_url 例子：
url = 'https://share.dmhy.org/topics/rss/rss.xml?keyword=' + parse.quote(key_word)
```

详细的方法可以看项目最近的commit，并且谢谢你提供的另一个网站，让我的收藏夹+1

**Comment by zx900930** [comment]
@Angel-Hair 哈哈，我还以为你弃坑， 自己改成蜜柑的了，可能台湾最近抓得严风声紧。
很多动漫网站上CF屏蔽欧美IP了，在欧洲的我只能换网站了
![image](https://user-images.githubusercontent.com/734749/90986144-de842c00-e580-11ea-8de2-0c6d110452d0.png)
