### ISSUE TITLE
出 师 未 捷 身 先 死

### ISSUE THREAD

**Issue by psygame** [Angel-Hair/XUN_Bot#9]
酷Q凉了

**Comment by Angel-Hair** [comment]
长 使 英 雄 泪 满 襟
\_(:3 」∠)\_
还是有一些代替方案的，可以移步这里查看：https://github.com/nonebot/nonebot/issues/217

不过我这儿酷Q Air还能跑，也不敢重启，所以一直没提供相关方案（其实就是懒……
